apiVersion: v1
kind: Pod
metadata:
  name: spark-job-pod
  labels:
    app: spark-job
spec:
  containers:
  - name: spark-job-pod
    image: testjob:0.1
    ports:
      - name: spark-driver
        containerPort: 7077
      - name: blockmanger
        containerPort: 7078
      - name: spark-ui
        containerPort: 4040
  restartPolicy: OnFailure