apiVersion: v1
kind: Service
metadata:
  name: spark-job-service
spec:
  selector:
    app: spark-job
  type: ClusterIP
  clusterIP: None
  ports:
    - name: driver
      protocol: TCP
      port: 7077
      targetPort: 7077
    - name: block-manager
      protocol: TCP
      port: 7078
      targetPort: 7078
    - name: spark-ui
      protocol: TCP
      port: 4040
      targetPort: 4040